spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
    
  datasource:
    url: jdbc:mysql://localhost:3306/casa_te
    username: root
    password: asas1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect 
    show-sql: true
    hibernate:
      ddl-auto: update #Remove on production